import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Science_Gothic = localFont({
  src: "../public/font/local/Science_Gothic.ttf",
  variable: "--font-science-gothic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "NyaaByte's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Science_Gothic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
