import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "components/Footer"; // 引入组件

const Science_Gothic = localFont({
  src: "../public/font/local/Science_Gothic.ttf",
  variable: "--font-science-gothic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "NyaaByte's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Science_Gothic.variable} antialiased`}>
        <main style={{ minHeight: '100vh' }}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}